/* data.js
   전체 단어 데이터: Lesson 05~08
   각 단어: [영단어, 뜻, 영영정의(없으면 ""), 품사, 예문]
   품사 코드: 동=동사, 명=명사, 형=형용사, 부=부사, 대=대명사, 숙=숙어/구
*/

const VOCAB_DATA = {
  "05": { name: "5단원", fullName: "Love, Act, Save!", words: [
    ["carry","휴대하다, 가지고 다니다","to hold and take something with you","동","She carries a small bag to school every day."],
    ["energy","에너지; 힘","natural power sources like electricity, fuel, or heat","명","Solar panels can turn sunlight into energy."],
    ["forget","잊다","","동","Don't forget to bring your umbrella."],
    ["nearby","가까운","","형","There is a nearby park where I like to walk."],
    ["plant","심다; 식물","","동/명","We planted a tree in the garden yesterday."],
    ["plastic","플라스틱으로 된; 플라스틱","","형/명","Please don't use plastic bags at the store."],
    ["pollution","오염, 공해","dirty or harmful things in air, water, or land","명","Air pollution is getting worse in big cities."],
    ["reusable","재사용할 수 있는","","형","I always carry a reusable bottle with me."],
    ["save","절약하다; 저축하다; 구하다; 보호하다","","동","We should save water when we brush our teeth."],
    ["terrible","극심한, 끔찍한","","형","The weather was terrible during our trip."],
    ["upcycling","업사이클링","turning old things into new, more valuable products","명","Upcycling turns old clothes into new bags."],
    ["waste","쓰레기; 낭비; 낭비하다","things that are not needed and thrown away","명/동","Don't waste your food; finish your plate."],
    ["slow down","(속도・진행을) 늦추다","","숙","Let's slow down and think about our plan."],
    ["take a shower","샤워를 하다","","숙","I take a shower every morning before school."],
    ["lose","잃어버리다","","동","I don't want to lose my new phone."],
    ["melt","녹다","to change from solid to liquid by heat","동","The ice began to melt in the sun."],
    ["part","역할; 일부; 부품; 부분","","명","Everyone should do their part to help the Earth."],
    ["pass","배설하다; 지나가다; 통과하다","to get rid of waste from the body","동","The car passed by our house quickly."],
    ["planet","행성","a large round body in space, like the Earth","명","Earth is the only planet we can live on."],
    ["recently","최근에","","부","I recently started learning to play the guitar."],
    ["recycle","재활용하다","to make old things into new materials","동","We recycle paper and plastic every week."],
    ["reduce","줄이다; 축소하다","","동","We can reduce waste by using less plastic."],
    ["reuse","재사용하다","to use something again without changing it","동","You can reuse this jar to store snacks."],
    ["rise","상승하다; 떠오르다","to become higher in level, amount, or number; to go up into the air","동","The sun rises in the east every morning."],
    ["scary","무서운, 겁나는","making you feel afraid or frightened","형","The movie was too scary for me to watch alone."],
    ["situation","상황, 처지","","명","The flood created a dangerous situation in the city."],
    ["tourist","여행객, 관광객","","명","Many tourists visit Venice every summer."],
    ["trash","쓰레기","","명","Please put your trash in the bin."],
    ["underwater","물속의, 수중의","","형","The city could be underwater in a few years."],
    ["add to","~에 더하다[보태다]","","숙","This news only adds to my worries."],
    ["be famous for","~로 유명하다","","숙","Venice is famous for its canals."],
    ["be made of","~로 만들어지다","","숙","This bag is made of old jeans."],
    ["do one's part","자기 역할을 하다","","숙","We should all do our part to help the planet."],
    ["get worse","악화되다","","숙","The traffic gets worse every winter."],
    ["make a difference","변화를 가져오다","","숙","Small actions can make a difference for the Earth."],
    ["put ~ in danger","~을 위험에 빠뜨리다","","숙","Pollution puts many animals in danger."],
    ["contact","연락하다","to get in touch with someone by phone, message, or meeting","동","Please contact me if you have any questions."],
    ["exchange","교환하다; 교환; 교류","","동/명","We exchanged phone numbers after the trip."],
    ["flea market","벼룩시장","","명","I found a nice bag at the flea market."],
    ["be in good condition","상태가 좋다; 건강이 양호하다","","숙","This old bike is still in good condition."],
    ["for sale","팔려고 내놓은","","숙","There were many old toys for sale online."],
    ["give it a try","시도하다, 한번 해보다","","숙","I've never done this before, but I'll give it a try."],
    ["make a posting","게시글을 올리다","","숙","She made a posting to sell her old skirt."],
    ["throw away","버리다","","숙","Don't throw away things you can still use."],
    ["campaign","캠페인, (사회적) 운동","planned actions to achieve something","명","Our school started a campaign to save water."],
    ["canal","운하, 수로","a man-made waterway for boats or for carrying water","명","Boats travel along the canals of Venice."],
    ["farm","농장; 경작하다","","명/동","My grandparents farm vegetables in the countryside."],
    ["flood","물에 잠기게 하다; 홍수","","동/명","Heavy rain caused the streets to flood."],
    ["global","세계적인; 지구의; 전반적인","about the whole world","형","Climate change is a global problem."],
    ["greenhouse gas","온실가스","a gas in the air that traps heat around the Earth","명","Cars release a lot of greenhouse gas."],
    ["habit","습관, 버릇","a usual way of acting or doing things that you repeat regularly","명","It's hard to change an old habit."],
    ["historic","역사상 중요한, 역사적인","very important in history","형","The city is famous for its historic buildings."],
    ["increase","증가하다; 증가시키다; 증가","","동/명","Eating more meat can increase greenhouse gases."],
    ["rarely","드물게, 좀처럼 ~하지 않는","","부","It rarely snows in this part of the country."],
    ["do better","더 잘하다","","숙","I want to do better on my next English test."],
    ["from now on","이제부터, 앞으로는 쭉","","숙","From now on, I will recycle more carefully."],
    ["celebrate","축하하다, 기념하다","to enjoy and honor a special day","동","We celebrated her birthday with a small party."],
    ["remake","새로 만들다, 다시 만들다","","동","They remade the old movie for a new audience."],
    ["rewrite","다시 쓰다, 고쳐 쓰다","","동","I had to rewrite my essay for homework."],
    ["underline","밑줄을 긋다; 강조하다","","동","Underline the important words in the sentence."],
    ["dangerous","위험한","","형","Swimming alone in the sea can be dangerous."],
    ["donate","기부하다, 기증하다","","동","We donated old clothes to people in need."],
    ["healthy","건강한","","형","Eating vegetables every day keeps you healthy."],
    ["arrive at","~에 도착하다","","숙","We arrived at the airport two hours early."],
    ["replay","재생하다","","동","Can you replay that song again?"],
    ["revisit","다시 방문하다","","동","I hope to revisit Venice again someday."],
    ["underground","지하에","","부","The subway runs underground beneath the city."],
    ["undersea","바다 밑의","","형","Scientists study strange undersea creatures."],
    ["seldom","좀처럼 ~하지 않는(=rarely)","","부","He seldom eats fast food."],
    ["lately","최근에(=recently)","","부","I haven't seen her much lately."],
    ["remember","기억하다(↔forget)","","동","Please remember to lock the door."],
    ["decrease","감소하다(↔increase)","","동","Pollution levels decreased after the new law."],
    ["gain","얻다(↔lose)","","동","You can gain a lot of knowledge from reading."],
    ["celebration","축하, 축하 행사","","명","The festival is a celebration of the harvest."],
    ["donation","기부, 기증","","명","We collected donations for the flood victims."],
    ["reduction","감소, 축소","","명","The city plans a big reduction in plastic waste."]
  ]},
  "06": { name: "6단원", fullName: "Growing Teens", words: [
    ["advice","조언, 충고","an opinion or a suggestion about what somebody should do in a particular situation","명","My teacher gave me good advice about studying."],
    ["article","(신문・잡지의) 글, 기사","","명","I read an interesting article about teens today."],
    ["clean","청소하다; 깨끗한","","동/형","Please clean your room before dinner."],
    ["enough","충분한; 충분히","","형/부","We don't have enough time to finish this."],
    ["fresh","신선한","","형","These vegetables are very fresh."],
    ["habit","습관, 버릇","","명","Getting enough sleep is a healthy habit."],
    ["information","정보","","명","The website gives useful information about the festival."],
    ["lower","낮추다; 줄이다","","동","Please lower your voice in the library."],
    ["manage","관리하다","","동","It's important to manage your time well."],
    ["messy","지저분한","","형","His desk is always messy."],
    ["online","온라인으로; 온라인의","","부/형","I do most of my homework online."],
    ["personal","개인의, 사적인","","형","That's a very personal question to ask."],
    ["post","게시하다","","동","She posted a photo of her lunch."],
    ["share","공유하다","","동","Please share your snacks with your friends."],
    ["stress","스트레스; 강조하다","","명/동","Too much homework can cause stress."],
    ["stretching","스트레칭","","명","Stretching before exercise helps prevent injury."],
    ["teen","십 대","","명","Many teens spend a lot of time online."],
    ["be careful about","~에 대해 조심하다","","숙","You should be careful about what you post online."],
    ["make a big difference","큰 차이를 만들다","","숙","A good night's sleep can make a big difference."],
    ["spend time (with)","(~와) 시간을 보내다","","숙","I like to spend time with my friends on weekends."],
    ["stay up late","늦게까지 깨어 있다","","숙","Don't stay up late before a test."],
    ["take a walk","산책하다","","숙","We took a walk in the park after dinner."],
    ["lose","지다; 잃다","","동","Our team lost the game by two points."],
    ["member","구성원[일원]; 회원","","명","Every member of the club has a job to do."],
    ["message","메시지","","명","She sent me a message this morning."],
    ["nurse","간호(사)","","명","The school nurse helped him with his cut."],
    ["office","사무실","","명","My mom works in an office downtown."],
    ["perform","공연하다","to entertain an audience by singing, acting, etc.","동","The band will perform at the school festival."],
    ["point","점수; 요점","","명","Our team scored the winning point."],
    ["principal","교장","the person in charge of a school","명","The principal spoke at the morning assembly."],
    ["proud","자랑스러워하는","feeling very happy and pleased because of something you have done","형","I felt proud after winning the contest."],
    ["pyramid","피라미드","","명","The cheerleaders formed a human pyramid."],
    ["quarter","(경기) 쿼터; 4분의 1","one of the four parts of the playing time of a game","명","The score was tied at the end of the first quarter."],
    ["recent","최근의","","형","Have you seen any recent news about the team?"],
    ["result","결과","something that is caused by something else that happened or was done before","명","I was happy with the result of the test."],
    ["save","저축하다","","동","I'm saving money to buy a new bike."],
    ["scream","소리치다","to cry out loudly because of pain, surprise, etc.","동","The fans screamed when their team scored."],
    ["shy","수줍은","","형","He's too shy to speak in front of the class."],
    ["spend","(돈・시간을) 쓰다, 소비하다","to use time or money for a particular purpose","동","I spent an hour doing my homework."],
    ["spread","퍼뜨리다","to cause something to be known by many people","동","Good news spreads quickly at school."],
    ["surprisingly","놀랍게도","","부","Surprisingly, the test was easier than expected."],
    ["survey","설문 조사","a study of people's opinions or behavior by asking questions","명","We did a survey about students' sleep habits."],
    ["trust","믿다, 신뢰하다","","동","You can trust him with your secret."],
    ["voice","목소리","","명","She has a loud, clear voice."],
    ["wonderfully","훌륭하게","","부","The choir sang wonderfully at the concert."],
    ["come on (+장소)","~에 올라오다[등장하다]","","숙","The singer came on stage to loud cheers."],
    ["give up","포기하다","","숙","Don't give up before the game even starts."],
    ["grow on trees","쉽게 손에 들어오다[생기다]","","숙","Money doesn't grow on trees, so save carefully."],
    ["in the air","공중에서, 허공에","","숙","There was excitement in the air before the game."],
    ["in the end","결국에, 마침내","","숙","In the end, our team won by one point."],
    ["lose by + 점수","~점 차이로 지다","","숙","We lost by just two points."],
    ["say hello","인사를 건네다","","숙","She waved and said hello to her friends."],
    ["spend + money + on","~에 돈을 쓰다","","숙","I spent all my money on concert tickets."],
    ["start from","~에서 시작되다","","숙","The idea for the club started from a small chat."],
    ["captain","(스포츠팀의) 주장","the leader of a group of people, especially a sports team","명","She was chosen as the captain of the team."],
    ["cheer","응원하다, 환호하다","to shout loudly in order to encourage someone","동/명","The crowd cheered loudly for the home team."],
    ["cheerleading","응원","","명","She joined the cheerleading squad this year."],
    ["choose","선택하다","","동","It's hard to choose between the two options."],
    ["condition","상태; 조건","the particular state that something or someone is in","명","The old bike is still in great condition."],
    ["court","(운동 경기용) 코트","","명","The players ran onto the basketball court."],
    ["crowd","관중; 군중","a large group of people who are together in one place","명","A huge crowd gathered to watch the game."],
    ["energy","에너지, 활력","","명","The players showed great energy in the final quarter."],
    ["festival","축제","","명","Our school festival is next Friday."],
    ["flip","뒤집다","to turn over into a different position with a sudden quick movement","동","He flipped the pancake in the pan."],
    ["follow","뒤를 잇다, 뒤따르다","","동","Please follow the instructions carefully."],
    ["halftime","(스포츠) 중간 휴식","a short break between the two halves of a sports game","명","The band performed during halftime."],
    ["healthcare","건강 관리","the activity or business of providing medical services","명","Nurses play an important role in healthcare."],
    ["human","인간의; 인간","","형/명","Every human being deserves respect."],
    ["life","생활; 삶","","명","Sports are an important part of school life."],
    ["lately","최근에","","부","I've been very busy lately."],
    ["be good at","~을 잘하다","","숙","She is good at solving math problems."],
    ["be good for","~에 좋다","","숙","Regular exercise is good for your health."],
    ["cheer for","~을 응원하다","","숙","We all cheered for our school team."],
    ["in front of","~앞에","","숙","The captain stood in front of the team."],
    ["pick up","~을 줍다","","숙","Please pick up the trash on the court."],
    ["environmental","환경의","","형","Our club joined an environmental clean-up event."],
    ["musical","음악의","","형","She plays several musical instruments well."],
    ["traditional","전통의","","형","This village has many traditional houses."],
    ["tip","조언, 충고(=advice)","","명","Here's a helpful tip for managing your time."],
    ["dirty","지저분한, 더러운(=messy)","","형","Don't leave your dirty shoes on the carpet."],
    ["private","개인의, 사적인(=personal)","","형","Please don't ask personal, private questions in class."],
    ["state","상태(=condition)","","명","Please describe the current state of the project."],
    ["select","선택하다(=choose)","","동","Select the best answer from the choices."],
    ["offline","오프라인으로(↔online)","","부","The app also works offline without internet."],
    ["death","죽음(↔life)","","명","The story is about life and death."],
    ["win","이기다(↔lose)","","동","Our team hopes to win the next game."],
    ["cause","원인(↔result)","","명","The cause of the accident is still unknown."]
  ]},
  "07": { name: "7단원", fullName: "Wonders in Words", words: [
    ["earworm","귀벌레","","명","That song became an earworm stuck in my head."],
    ["example","예, 예시","","명","Can you give me an example of a good habit?"],
    ["grow","재배하다; 자라다","","동","We grow tomatoes in our garden every summer."],
    ["host","진행자; 주인","","명/동","The show's host welcomed the guests warmly."],
    ["information","정보","","명","This book has a lot of useful information."],
    ["latest","최신의[최근의]","","형","Have you heard the latest news about the trip?"],
    ["letter","글자; 편지","","명","She wrote a letter to her best friend."],
    ["quickly","빨리","","부","He quickly finished his homework after school."],
    ["repeat","반복하다","","동","Could you repeat that, please?"],
    ["sculpture","조각(상)","","명","The park has a famous stone sculpture."],
    ["stressed","스트레스 받는","","형","I feel stressed before big tests."],
    ["technology","기술","","명","New technology has changed how we communicate."],
    ["communicate with","~와 의사소통하다","","숙","It's important to communicate with your teammates."],
    ["in front of","~의 앞에(서)","","숙","He stood in front of the class to speak."],
    ["put on","(옷이나 신발 등을) 입다[신다]","","숙","Put on your coat before you go outside."],
    ["take a photo","사진을 찍다","","숙","Let's take a photo in front of the castle."],
    ["prepare","준비하다","to make plans or arrangements for something that will happen in the future","동","We need to prepare for the school play."],
    ["promise","약속하다; 약속","","동/명","I promise to keep your secret."],
    ["refuse","거절하다; 거부하다","to say you are not willing to do something","동","He refused to give up his seat."],
    ["reply","대답하다","","동","She didn't reply to my message yet."],
    ["result","결과","","명","The result of the vote surprised everyone."],
    ["reveal","드러내다, 폭로하다","to make known or show something that is surprising or that was previously secret","동","The magician revealed his secret trick."],
    ["secret","비밀","a fact or a piece of information kept hidden from others","명","Can you keep a secret?"],
    ["situation","상황","","명","It was an awkward situation for both of us."],
    ["spill","쏟다, 흘리다","to cause to flow or fall over the edge of something","동","Be careful not to spill your juice."],
    ["sporting","스포츠의","","형","The sporting event drew a large crowd."],
    ["stage","무대","","명","The singer walked onto the stage."],
    ["success","성공","achieving the results you wanted or hoped for","명","Hard work is the key to success."],
    ["surprised","놀란","","형","I was surprised to see her at the party."],
    ["vote","투표하다; 투표","to express your choice, especially by marking a paper or raising your hand","동/명","We voted for our class president today."],
    ["wish","~을 빌다; 바라다, 소원하다","","동","I wish I could travel around the world."],
    ["be about to + 동사원형","막 ~하려는 참이다","","숙","The movie is about to start, so hurry up."],
    ["because of","~때문에","","숙","The game was canceled because of the rain."],
    ["come from","~에서 유래하다","","숙","This word comes from an old English phrase."],
    ["each other","서로","","숙","The two teams respect each other."],
    ["go away","사라지다, 없어지다","","숙","I hope this headache goes away soon."],
    ["go up","(무대에서) 커튼이 올라가다","","숙","The curtain went up as the play began."],
    ["keep a secret","비밀을 지키다","","숙","I promise I can keep a secret."],
    ["keep one's promise","약속을 지키다","","숙","He always keeps his promises."],
    ["not good at","~을 잘하지 못하는","","숙","I'm not good at singing in front of people."],
    ["over time","시간이 흐르면서","","숙","The idiom's meaning changed over time."],
    ["put A in B","A를 B에 넣다","","숙","She put the letter in the drawer."],
    ["sound like","~처럼 들리다","","숙","That plan sounds like a great idea."],
    ["spill the beans","비밀을 말하다, 폭로하다","","숙","Don't spill the beans about the surprise party."],
    ["actually","실제로, 사실은","in fact or really","부","I actually enjoyed the movie more than I expected."],
    ["ancient","고대의","from a time long ago in history","형","The museum has many ancient sculptures."],
    ["bean","콩","","명","We planted beans in the school garden."],
    ["cancel","취소하다","to stop something that was planned from happening","동","The trip was canceled because of the storm."],
    ["break","부러뜨리다; 부수다","","동","Be careful not to break the vase."],
    ["century","세기, 100년","","명","This castle was built in the twelfth century."],
    ["complete","완료하다; 완전한","to finish doing or making something","동/형","Please complete the form before you leave."],
    ["curtain","커튼","","명","The actors bowed as the curtain closed."],
    ["disappointed","실망한","unhappy because something was not as good as expected","형","She was disappointed when the trip was canceled."],
    ["expression","표현","the act of showing thoughts or feelings in words or actions","명","His face had a surprised expression."],
    ["event","행사","something important that happens","명","The school festival is a big event every year."],
    ["idiom","관용구, 숙어","","명","'Break a leg' is a famous English idiom."],
    ["jar","항아리, 단지","","명","She kept cookies in a glass jar."],
    ["mean","의미하다","","동","What does this word mean?"],
    ["nervous","긴장한, 불안한","","형","I always feel nervous before a speech."],
    ["offer","제안; 제안하다","the act of giving someone an opportunity to accept something","명/동","He offered to help me with my homework."],
    ["perform","공연하다","","동","The choir will perform at the concert tonight."],
    ["phrase","어구","a group of words that express one idea but not a complete sentence","명","Try to use this phrase in a sentence."],
    ["play","연극; 희곡; 놀이; 놀다","","명/동","Our class is putting on a play next month."],
    ["politely","예의 바르게","in a way that shows good manners","부","She politely asked for more time."],
    ["director","감독","","명","The movie director gave a short speech."],
    ["firefighter","소방관","","명","The firefighter rescued the cat from the tree."],
    ["refrigerator","냉장고","","명","Put the milk back in the refrigerator."],
    ["respect","존경하다","","동","We should respect our teachers and friends."],
    ["trust","신뢰하다, 믿다","","동","I trust you to keep this secret."],
    ["arrive at","~에 도착하다","","숙","We arrived at school just in time."],
    ["connect to","~에 연결[접속]하다","","숙","This cable connects to the computer."],
    ["give up","포기하다","","숙","Never give up on your dreams."],
    ["have a hard time (in)","~하느라 힘든 시간을 보내다","","숙","I had a hard time solving that math problem."],
    ["put out","불을 끄다","","숙","The firefighters quickly put out the fire."],
    ["mysterious","신비로운","","형","There was a mysterious light in the old house."],
    ["famous","유명한","","형","This idiom is famous all over the world."],
    ["instance","예, 사례(=example)","","명","For instance, 'raining cats and dogs' means raining heavily."],
    ["raise","재배하다, 기르다(=grow)","","동","Farmers raise chickens on this farm."],
    ["newest","최신의(=latest)","","형","This is the newest phone from the company."],
    ["rapidly","빨리(=quickly)","","부","The city is growing rapidly."],
    ["entirely","완전히(=completely)","","부","I entirely agree with your idea."],
    ["modern","현대의(↔ancient)","","형","The building has a modern design."],
    ["satisfied","만족한(↔disappointed)","","형","I was satisfied with my test score."],
    ["calm","차분한(↔nervous)","","형","Try to stay calm during the exam."],
    ["rudely","무례하게(↔politely)","","부","He rudely interrupted the teacher."],
    ["accept","수락하다(↔refuse)","","동","She accepted the invitation happily."],
    ["ask","질문하다(↔reply)","","동","Feel free to ask any questions."],
    ["hide","숨기다(↔reveal)","","동","The cat likes to hide under the bed."]
  ]},
  "08": { name: "8단원", fullName: "Festival Fun", words: [
    ["activity","활동","","명","Swimming is my favorite summer activity."],
    ["exciting","흥미진진한, 신나는","","형","The festival was really exciting this year."],
    ["fantastic","환상적인, 멋진","extremely good","형","We had a fantastic time at the carnival."],
    ["festival","축제","","명","The winter festival attracts many visitors."],
    ["fishing","낚시","","명","My dad and I went fishing last weekend."],
    ["fresh","신선한","","형","The market sells fresh fruit every morning."],
    ["full","배부른","","형","I'm too full to eat any more."],
    ["icy","얼음에 뒤덮인","covered with ice","형","The road was icy after the snowstorm."],
    ["muddy","진흙투성이의","","형","Our shoes got muddy after the hike."],
    ["perfect","완벽한, 완전한","","형","The weather was perfect for the festival."],
    ["ride","(탈것을) 타다","","동","We rode the roller coaster three times."],
    ["roast","(불에) 굽다, 볶다","","동","We roasted marshmallows over the campfire."],
    ["slide","미끄럼틀; 활강장; 미끄러지다","to move smoothly over a surface","동/명","The kids loved sliding down the ice slide."],
    ["soft","부드러운","","형","The snow felt soft under our boots."],
    ["surround","둘러싸다, 에워싸다","","동","Mountains surround the small town."],
    ["taste","맛보다; 맛","","동/명","Can I taste your ice cream?"],
    ["view","경치, 경관; 바라보다","what you can see from a particular place","명/동","The view from the castle was amazing."],
    ["go + 동명사","~하러 가다","","숙","We went camping last summer."],
    ["look forward to + 동명사","~하는 것을 기대하다","","숙","I'm looking forward to the festival next week."],
    ["participate in","~에 참가[참여]하다","","숙","Many students participated in the sports day."],
    ["try out","~을 시험 삼아 해 보다","","숙","Let's try out the new ice slide."],
    ["walk along","~을 따라 걷다","","숙","We walked along the river after lunch."],
    ["walk around","~주변을 돌아다니다","","숙","We walked around the castle for an hour."],
    ["amazing","굉장한, 놀라운","","형","The fireworks show was amazing."],
    ["both","둘 다, 양쪽; 양쪽의","","형/대","Both of my parents came to the festival."],
    ["carnival","카니발, 축제","an event where people gather to celebrate something","명","The winter carnival lasts for two weeks."],
    ["castle","성","a large building with thick walls which was built to protect people in the past","명","The old castle stands on top of the hill."],
    ["cheerful","명랑한, 쾌활한","","형","Everyone at the festival looked cheerful."],
    ["colorful","형형색색의","","형","The parade had many colorful costumes."],
    ["drink","음료; 마시다","","명/동","We drank hot chocolate to stay warm."],
    ["famous","유명한","","형","This festival is famous for its ice sculptures."],
    ["follow","따라가다","","동","Please follow the path to the main stage."],
    ["forget","잊다","","동","I'll never forget this amazing festival."],
    ["friendly","친절한; 우호적인","","형","The mascot was friendly and fun to watch."],
    ["hold","열다, 개최하다","to have or organize an event, meeting, or activity","동","The town holds this festival every winter."],
    ["huge","거대한","","형","There was a huge ice castle in the square."],
    ["light","빛, 불빛, 조명; 밝히다","","명/동","They lit up the whole street with lights."],
    ["mascot","마스코트","a person, animal, plant or object that represents a group or special event","명","The festival mascot waved to the children."],
    ["mask","탈, 가면","","명","Everyone wore colorful masks at the carnival."],
    ["memory","기억","something that you remember from the past","명","This trip will be a great memory."],
    ["narrow","좁은","having a small distance from one side to the other","형","We walked through a narrow street in the old town."],
    ["performance","공연","","명","The dance performance was the highlight of the night."],
    ["place","놓다","to put something in a particular position","동","Please place your bag under the seat."],
    ["pour","붓다","to make something flow in a steady stream from or into a container or place","동","She poured hot chocolate into our cups."],
    ["race","경주; 경주하다","a competition between people, animals, vehicles, etc.","명/동","We watched the dog sled race in the snow."],
    ["roll","굴리다","to cause something to move by turning over and over","동","The kids rolled snowballs to make a snowman."],
    ["sculpture","조각(품)","a piece of art made of stone, metal, clay, etc.","명","The ice sculpture looked like a real castle."],
    ["shine","빛나다","","동","The lights shine brightly at night."],
    ["sled","썰매; 썰매를 타다","","명/동","We rode a sled down the snowy hill."],
    ["speed","속도","","명","The sled reached a high speed down the hill."],
    ["stick","막대기","","명","We roasted marshmallows on a long stick."],
    ["stuck","갇힌; 꼼짝 못하는","difficult or unable to move from a position or place","형","Our car got stuck in the snow."],
    ["treat","특별한 것[대접]; 대접하다","something special that you enjoy, especially food that is given to you","명/동","Hot chocolate was a nice treat after skating."],
    ["a lot of","많은","","숙","There were a lot of people at the festival."],
    ["unforgettable","잊지 못할, 잊을 수 없는","difficult or impossible to forget","형","It was an unforgettable night full of lights."],
    ["be made of","~로 만들어지다","","숙","The castle was made of ice."],
    ["be made up of","~로 구성되다","","숙","The festival is made up of many small events."],
    ["be stuck in","~에 갇히다","","숙","We got stuck in traffic on the way home."],
    ["between A and B","A와 B 사이에","","숙","The stage is set between the two ice statues."],
    ["get on","~을 타다","","숙","We got on the sled and slid down the hill."],
    ["get to","~에 도착하다, ~에 이르다","","숙","It took an hour to get to the festival."],
    ["make it","해내다, 성공하다","","숙","We made it to the festival just in time."],
    ["on one's left[right]","~의 왼쪽[오른쪽]에","","숙","The food stalls are on your right."],
    ["roll ~ around","~을 돌돌 말다","","숙","He rolled the snowball around to make it bigger."],
    ["slide down","미끄러져 내려가다","","숙","We slid down the icy hill many times."],
    ["take a look (at)","~을 보다","","숙","Come take a look at the ice sculptures."],
    ["take place in","~에서 열리다[일어나다]","","숙","The festival takes place in a small mountain town."],
    ["cancel","취소하다","","동","The outdoor show was canceled due to the storm."],
    ["choose","선택하다","","동","It was hard to choose a favorite ice sculpture."],
    ["lastly","마지막으로","","부","Lastly, we watched the fireworks show."],
    ["mix","섞다","","동","Mix the hot chocolate well before drinking."],
    ["prepare","준비하다","","동","The town spends months preparing for the festival."],
    ["yell","소리치다","","동","The kids yelled with excitement on the sled."],
    ["fall asleep","잠들다","","숙","She fell asleep on the bus ride home."],
    ["wait in line","줄을 서서 기다리다","","숙","We waited in line for the ice slide."],
    ["lucky","운 좋은","","형","We were lucky to get good seats for the show."],
    ["tasty","맛있는","","형","The festival food was really tasty."],
    ["awesome","굉장한(=amazing)","","형","The whole festival was awesome."],
    ["competition","경주, 경쟁(=race)","","명","The snow sculpture competition was fun to watch."],
    ["boring","지루한(↔exciting)","","형","Waiting in a long line can be boring."],
    ["hungry","배고픈(↔full)","","형","After the walk, we were all hungry."],
    ["separate","분리하다(↔mix)","","동","We separated into small groups for the tour."],
    ["hard","단단한(↔soft)","","형","The ice was too hard to break."],
    ["sweet","달콤한","","형","The hot chocolate was warm and sweet."],
    ["bitter","쓴(↔sweet)","","형","The cold wind felt bitter on our faces."],
    ["tiny","아주 작은(↔huge)","","형","Tiny snowflakes fell softly all evening."],
    ["wide","넓은(↔narrow)","","형","The main street was wide enough for the parade."],
    ["push","밀다(↔pull)","","동","We had to push the sled up the hill."],
    ["pull","당기다(↔push)","","동","He pulled the sled behind him."]
  ]}
};

if (typeof module !== "undefined" && module.exports) module.exports = VOCAB_DATA;
